### ISSUE TITLE
خطأ مدوِّي" (ترجمة إلى العربية

### ISSUE THREAD

**Issue by Turbo-Alhamed** [Th3ps/discord-database-bot#1]
تم تسريب الرمز ورأيته (ترجمة إلى العربية

**Comment by Th3ps** [comment]
كرًا جزيلاً على المشاركة! تحياتي!

**Comment by Turbo-Alhamed** [comment]
يحيا سوريا

**Comment by Th3ps** [comment]
Thank you for your contribution, I'm closing the Issue.
